version: '3.8'
services:
  postgres:
    image: "postgres:16.3"
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./local-db-init.sql:/docker-entrypoint-initdb.d/init.sql
