CREATE TABLE IF NOT EXISTS fagsak_id_mapping (soknad_id TEXT PRIMARY KEY, fagsak_id BIGSERIAL NOT NULL);
CREATE SEQUENCE IF NOT EXISTS fagsak_id_mapping_fagsak_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
