apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: ekspertbistand-frontend-mock
  namespace: fager
  labels:
    team: fager
spec:
  image: {{{ image }}}
  port: 4000
  ingresses:
    - https://arbeidsgiver-dev.ansatt.dev.nav.no/ekspertbistand
  env:
    - name: BASE_PATH
      value: "/ekspertbistand"

  replicas:
    min: 1
    max: 1

  tokenx:
    enabled: false

  idporten:
    enabled: false

  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  liveness:
    path: /ekspertbistand/internal/isAlive

  readiness:
    path: /ekspertbistand/internal/isAlive
