apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: ekspertbistand-saksbehandling
  namespace: fager
  labels:
    team: fager
spec:
  image: {{ image }}
  port: 4000
  ingresses:
    - https://ekspertbistand-saksbehandling.intern.dev.nav.no

  replicas:
    min: 1
    max: 1

  azure:
    application:
      enabled: true
      claims:
        groups:
          # saksbehandler-gruppe
          - id: 1b3a2c4d-d620-4fcf-a29b-a6cdadf29680
          # Beslutter-gruppe
          - id: 79985315-b2de-40b8-a740-9510796993c6
          # Fortrolig adresse gruppe
          # - id: TODO
          # Strengt fortrolig adresse gruppe
          # - id: TODO
    sidecar:
      enabled: true
      autoLogin: false

  env:
    - name: EKSPERTBISTAND_API_BASEURL
      value: "http://ekspertbistand-backend"
    - name: EKSPERTBISTAND_API_AUDIENCE
      value: "api://dev-gcp.fager.ekspertbistand-backend/.default"

  accessPolicy:
    outbound:
      rules:
        - application: ekspertbistand-backend

  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 512Mi

  liveness:
    path: /internal/isAlive

  readiness:
    path: /internal/isAlive
