apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: ekspertbistand-frontend
  namespace: fager
  labels:
    team: fager
spec:
  image: {{ image }}
  port: 4000
  ingresses:
    - https://arbeidsgiver.intern.dev.nav.no/ekspertbistand
  env:
    - name: BASE_PATH
      value: "/ekspertbistand"
    - name: SCHEMA_API_BASE_URL
      value: "http://ekspertbistand-backend"
    - name: SCHEMA_API_AUDIENCE
      value: "dev-gcp:fager:ekspertbistand-backend"

  replicas:
    min: 2
    max: 2

  tokenx:
    enabled: true

  idporten:
    enabled: true
    sidecar:
      enabled: true

  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  liveness:
    path: /ekspertbistand/api/health
    initialDelay: 10
    periodSeconds: 10

  readiness:
    path: /ekspertbistand/api/health
    initialDelay: 3
    periodSeconds: 5

  accessPolicy:
    outbound:
      rules:
        - application: ekspertbistand-backend
