apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: ekspertbistand-backend
  namespace: fager
  labels:
    team: fager
spec:
  image: {{{ image }}}

  liveness:
    path: /internal/isalive

  readiness:
    path: /internal/isready

  prometheus:
    enabled: true
    path: /internal/prometheus

  observability:
    autoInstrumentation:
      enabled: true
      runtime: java

  resources:
    requests:
      memory: 512Mi
    limits:
      memory: 1024Mi

  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  gcp:
    sqlInstances:
      - name: ekspertbistand-backend
        type: POSTGRES_18
        tier: db-f1-micro
        diskAutoresize: true
        highAvailability: false
        databases:
          - name: ekspertbistand
            envVarPrefix: DB

  accessPolicy:
    inbound:
      rules:
        - application: ekspertbistand-frontend
    outbound:
      external:
        - host: pdl-api.dev-fss-pub.nais.io
      rules:
        - application: logging
          namespace: nais-system
        - application: notifikasjon-produsent-api
          namespace: fager
        - application: arbeidsgiver-altinn-tilganger
          namespace: fager

