apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: ekspertbistand-frontend
  namespace: fager
  labels:
    team: fager
spec:
  image: {{ image }}
  port: 4000
  ingresses:
    - https://arbeidsgiver.intern.nav.no/ekspertbistand
  env:
    - name: BASE_PATH
      value: "/ekspertbistand"
    - name: EKSPERTBISTAND_API_BASEURL
      value: "http://ekspertbistand-backend"
    - name: EKSPERTBISTAND_API_AUDIENCE
      value: "prod-gcp:fager:ekspertbistand-backend"

  replicas:
    min: 2
    max: 2

  tokenx:
    enabled: true

  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: false

  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki

  resources:
    limits:
      memory: 512Mi

  liveness:
    path: /ekspertbistand/internal/isAlive

  readiness:
    path: /ekspertbistand/internal/isAlive

  accessPolicy:
    outbound:
      rules:
        - application: ekspertbistand-backend
