name: Manuell deploy dev backend
on:
  workflow_dispatch:

jobs:
  dev-deploy:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: nais/login@v0
        id: login
        with:
          team: fager

      - uses: nais/deploy/actions/deploy@v2
        name: Deploy dev-gcp
        env:
          VAR: image=${{ steps.login.outputs.registry }}/ekspertbistand-backend:${{ github.sha }}
          RESOURCE: nais/dev-gcp-altinn-backend.yaml
          CLUSTER: dev-gcp

